del *.ncb /Q /S /A
del *.pdb /Q /S /A
del *.obj /Q /S /A
del *.suo /Q /S /A
del *.res /Q /S /A
del *.suo /Q /S /A
del BuildLog.htm /Q /S /A
del *.idb /Q /S /A
del *.pch /Q /S /A
del *.sdf /Q /S /A
del *.user /Q /S /A
del *.sbr /Q /S /A